# Generated by Django 3.1.2 on 2020-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201025_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.AlterField(
            model_name='task',
            name='do_by',
            field=models.DateTimeField(null=True),
        ),
    ]
